services:
  # Api blog
  api-blog:
    container_name: api-blog
    build: ../apiBlog
    security_opt:
      - no-new-privileges:true
    restart: always
    deploy:
      replicas: 1
    env_file:
      - ../apiBlog/.env
    depends_on:
      - db
  # Api gateway:
  gateway:
    container_name: gateway
    build: ../gateway
    security_opt:
      - no-new-privileges:true
    restart: always
    depends_on:
      - api-blog
    ports:
      - 5000:5000
    env_file:
      - ../gateway/.env

  # Api auth
  dapiauth:
    container_name: dapiauth
    build: ../auth
    security_opt:
      - no-new-privileges:true
    restart: always
    depends_on:
      - db
    volumes:
      - ../auth/themes:/opt/keycloak/themes
    ports:
      - 8080:8080
    command: start --optimized --import-realm --spi-theme-welcome-theme=inssat
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
  
  # MariaDB
  db:
    container_name: db
    image: mariadb:latest
    security_opt:
      - no-new-privileges:true
    restart: always
    command: ["--init-file=/data/application/init.sql"]
    volumes:
        - db_data:/var/lib/mysql
        - ./init.sql:/data/application/init.sql
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: 4mvstWAvkShcgsOMG5fh

volumes:
  db_data:
