CREATE DATABASE IF NOT EXISTS intranet_prod;
CREATE DATABASE IF NOT EXISTS intranet_test;
CREATE DATABASE IF NOT EXISTS intranet_dev;
CREATE DATABASE IF NOT EXISTS intranet_demo;
CREATE DATABASE IF NOT EXISTS intranet_auth;